### PR TITLE
subclipse 1.8.x support

### PR DESCRIPTION
**Pull request by vmi**
This patch changes the supporting subclipse version into 1.8.x.

### CODE REVIEW

**Comment by vmi** [comment]
Do any problems exist in my patch?

**Comment by niphor** [comment]
could you tell me how to compile it?(i'm beginner of using maven)
when i use "clean compile" or any other command.(using maven 3.0.3)

it reports such error below:

[INFO] Adding repository http://subclipse.tigris.org/update_1.8.x
一月 31, 2012 11:12:53 上午 org.apache.commons.httpclient.HttpMethodBase processCookieHeaders
警告: Cookie rejected: "$Version=0; JSESSIONID=DC604F52215EAAA0CA5FA4D57E369522; $Path=/servlets". Illegal path attribute "/servlets". Path of origin: "/update_1.8.x/artifacts.jar"
一月 31, 2012 11:12:54 上午 org.apache.commons.httpclient.HttpMethodBase processCookieHeaders
警告: Cookie rejected: "$Version=0; JSESSIONID=C74D628971EF349F8C9AE998F710B1B7; $Path=/servlets". Illegal path attribute "/servlets". Path of origin: "/update_1.8.x/artifacts.xml"
[INFO] Cannot complete the request.  Generating details.
[INFO] {org.osgi.framework.executionenvironment=OSGi/Minimum-1.0,OSGi/Minimum-1.1, osgi.ws=win32, osgi.arch=x86, osgi.os=win32, org.eclipse.update.install.features=true, org.osgi.framework.system.packages=}
[INFO] [You requested to install 'com.collabnet.subversion.merge.feature.feature.group [3.0.4]' but it could not be found]
[ERROR] Internal error: java.lang.RuntimeException: org.eclipse.equinox.p2.core.ProvisionException: No solution found because the problem is unsatisfiable. -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.eclipse.equinox.p2.core.ProvisionException: No solution found because the problem is unsatisfiable.

sorry for my poor english

**Comment by jdkcn** [comment]
I'm waiting this patch.

Thanks

**Comment by vmi** [comment]
Hi.

I used Eclise to build. not command line.
1. check out the source from github by Eclipse + m2e + EGit + m2eclipse-egit.
2. open org.sonatype.m2e.subclipse.feature/feature.xml
3. push feature export button at top-right.

compiled binary:
http://vmi.jp/software/java/m2e-subclipse-bin.zip

**Comment by jdkcn** [comment]
Thanks vmi, so kind of you.

I'll try later and hope sonatype accept this pull request soon.

**Comment by niphor** [comment]
Hi vim,Thank you for your help!
Although, eclipse shows some error about:
some class need import "org.tigris.subversion.subclipse.core" package,but export successfully.

I changed maven 3.0.3 to 2.2.1
while using "mvn clean install",it shows the error:
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'org.eclipse.tycho:ty
cho-packaging-plugin:0.12.0:build-qualifier': Unable to find the mojo 'build-qua
lifier' (or one of its required components) in the plugin 'org.eclipse.tycho:tyc
ho-packaging-plugin'
Component descriptor cannot be found in the component repository: org.codehaus.p
lexus.logging.Logger.

maybe,it needs some specific commands or parameters rather than simply using "mvn clean install"

I think i really need much more reading and practising

**Comment by vmi** [comment]
> some class need import "org.tigris.subversion.subclipse.core" package,but export successfully.

oh, please install Subclipse plugin to your Eclipse.

> I'll try later and hope sonatype accept this pull request soon.

Good news!

**Comment by niphor** [comment]
I have Subclipse installed in my eclipse already.(v1.8.x) 
but if i import the package,it will report an error,because it only allows  1.6.0<=x<1.7.0
so it seems i must edit org.sonatype.m2e.subclipse/META-INF/MANIFEST.MF to allow 1.8.x

**Comment by vmi** [comment]
My patch fixes it!:-)

**Comment by moldowan** [comment]
I can confirm that placing the contents of the zip-file that vmi provided in the eclipse dropins folder broght back the svn scm handler!
Well done and thank you, vmi!

Too bad that no one from the m2e team seems to be willing to apply this patch...

**Comment by LosD** [comment]
That worked wonders, thanks vmi!

**Comment by samlevin** [comment]
Pleaseeeee let me know how I can install this. I put it in my "dropins" folder, but I do not see the scm handler (on the checkout maven projects via scm dialog) ... also, I do not see it in the marketplace (I am using subclipse 1.8.x with eclipse helios SR2) THANK YOUUUU

**Comment by samlevin** [comment]
Bad news. m2e subclipse connector has been removed from the discovery maven page. No idea how to get it now...

**Comment by LosD** [comment]
sjl2024: There is a compiled binary [right here](https://github.com/sonatype/m2eclipse-subclipse/pull/4#issuecomment-3761903)

Extract that zip into a subfolder of the dropins folder (i.e. m2e-subclipse), and you are ready to go.

Now we just need Sonatype to pull their heads out of their asses, and merge this ASAP.

**Comment by samlevin** [comment]
OK ... but big problem. The m2e-connector-subclipse has been moved from eclipse marketplace maven discovery. Must you have the connector installed before upgrading to supclipse 1.8.x? I do not have the connector installed, which is why I think the patch is not working for me. HOW can I find a link to the old connector somehow? Why was it removed? Ugh!

**Comment by LosD** [comment]
You do not need to have the connector installed first. Just install/update to Subclipse 1.8.x, and then quit Eclipse. Dump the contents of that Zip into dropins/m2e-subclipse. After that, you should be able to i.e. right click a folder in the SVN Repository Explorer Perspective and choose "Check out as Maven Project".

If you haven't connected to a repository yet, do that first, the Maven import wizard has problems until then.

**Comment by samlevin** [comment]
Ah, so I cannot do through Import > Import Maven Projects from SCM?

**Comment by LosD** [comment]
Yes, but only _after_ you connected to a repository for the first time (at least on my installation, first time i tried using the Maven import wizard, the svn browse window was just empty).

**Comment by samlevin** [comment]
Thank you - last question - Must I install m2e before I can check out a project as a Maven project? (Else how will know its maven proj)? Thanks!!!

**Comment by LosD** [comment]
I never tried, but I would certainly think so.

However, if you already checked out something using SVN (As an external client) before you installed m2e, you can just use the "Import Maven Project" (I think that's what it's called), and it will work perfectly fine.

I you imported using Subclipse directly as a generic project, you can use the Configure->As Maven Project context menu on the project.

m2e-subclipse is not really _needed_ for m2e + SVN, it just make things a lot simpler, especially when you want to import a dependent project that is stored in SVN.

**Comment by samlevin** [comment]
How do I "connected to a repository for the first time "???? How can I connect to svn repo without checking out project?

**Comment by LosD** [comment]
You just open up the Subclipse SVN Repository Perspective, right-click, and choose New->Repository Location.

I can't remember if it asks for login credentials when you create it. If it doesn't, you probably also need to connect to the repository (just try to browse it, then it should ask for the login, if any is needed).

**Comment by samlevin** [comment]
I tried everything you've said, but the box was still blank after. Gah.

**Comment by LosD** [comment]
Strange. Do the SVN Repository Explorer Perspective _Check out as Maven Project_ fail as well?

**Comment by markphip** [comment]
I have applied this pull request and another to my own fork and published a build on the Subclipse website:  https://github.com/markphip/m2eclipse-subclipse

Subclipse does not use Maven, so I am not positive the build works.  Hopefully someone can confirm.  I am willing to keep an up to date build available in terms of the Subclipse API usage.  I will also accept pull requests for other features on the Maven side.

If the build works, maybe we can get it listed back in the m2e marketplace.

**Comment by bluebilt** [comment]
Thanks markphip, I can confirm your update site works like a charm!

http://subclipse.tigris.org/m2eclipse/1.0

**Pull request closed without merging**
